// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9XPU-UmX0KyQz9iXBLU_7wYevxCmhp58',
    appId: '1:55758545449:web:4348151ac4c311148cf238',
    messagingSenderId: '55758545449',
    projectId: 'sihijau-app',
    authDomain: 'sihijau-app.firebaseapp.com',
    storageBucket: 'sihijau-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmK6KuoVmE5BmxjelqHsPOjqTMwrqTwjg',
    appId: '1:55758545449:android:581feaaa285d04608cf238',
    messagingSenderId: '55758545449',
    projectId: 'sihijau-app',
    storageBucket: 'sihijau-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACrTC4qC4EDaAEupkeOZhElZQTAuZcwZ4',
    appId: '1:55758545449:ios:f0c3f76203c0337b8cf238',
    messagingSenderId: '55758545449',
    projectId: 'sihijau-app',
    storageBucket: 'sihijau-app.firebasestorage.app',
    iosBundleId: 'com.example.sihijauApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACrTC4qC4EDaAEupkeOZhElZQTAuZcwZ4',
    appId: '1:55758545449:ios:f0c3f76203c0337b8cf238',
    messagingSenderId: '55758545449',
    projectId: 'sihijau-app',
    storageBucket: 'sihijau-app.firebasestorage.app',
    iosBundleId: 'com.example.sihijauApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9XPU-UmX0KyQz9iXBLU_7wYevxCmhp58',
    appId: '1:55758545449:web:6b15cd824e1df1ed8cf238',
    messagingSenderId: '55758545449',
    projectId: 'sihijau-app',
    authDomain: 'sihijau-app.firebaseapp.com',
    storageBucket: 'sihijau-app.firebasestorage.app',
  );
}
